
<?php

if (!empty($this->_['error'])) {
    echo $this->_['error'];
}
?>
    <?php
    $headerGeschaeft = ($this->_['geschaeft'] == "hauptgeschaeft" ? "Hauptgeschäft" : "Rheinstraße");
    echo '<div class="row" style="margin-bottom:20px;"><div class="col-lg-12"><div class="subnavi text-justify"><a href="'.BASE_URL.'admin/mittagstisch?geschaeft=hauptgeschaeft&token='.$this->_['token'].'">Hauptgeschäft</a> <a href="'.BASE_URL.'admin/mittagstisch?geschaeft=rheinstrasse&token='.$this->_['token'].'">Rheinstrasse</a></div></div></div>';
    echo '<div class="row"><div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div><div class="col-lg-8 col-md-12"><h3 style="text-transform:capitalize; text-align:center">'.$headerGeschaeft.'</h3></div><div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div></div>';
if (!empty($this->_['tableList'])) {
        foreach ($this->_['tableList'] as $value) {
            if (empty($value['startDate'])) {
                continue;
            }


            echo '<form action="'.BASE_URL.'postMittagstisch?geschaeft='.$this->_['geschaeft'].'&token='.$this->_['token'].'" method="POST"  accept-charset="UTF-8">';
            if (!empty($this->_['editID']) && $this->_['editID'] == $value['ID']) {
                echo '<input type="hidden" name="tableID" value="'.$value['ID'].'" />';
            }
            echo '
                   <div class="row">
                    <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                    <div class="col-lg-6 col-sm-12 k_table-overview">
                        <strong>Mittagstisch</strong><br/>
                        <span>KW '.$value['KW'].'</span><br/><br/>
                    </div>
                    <div class="col-lg-2 col-sm-12 k_table-overview">
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="table'.$value['ID'].'-startDateAddon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Vom:</span>
                            <input type="text" name="startDate['.$value['ID'].']" class="form-control" placeholder="01.01.2016" value="'.$value['startDate']->format("d.m.Y").'" aria-describedby="table'.$value['ID'].'-startDateAddon">
                        </div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="table'.$value['ID'].'-endDateAddon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> &nbsp;&nbsp;Bis:</span>
                            <input type="text" name="endDate['.$value['ID'].']" class="form-control" placeholder="01.01.2016" value="'.$value['endDate']->format("d.m.Y").'" aria-describedby="table'.$value['ID'].'-endDateAddon">
                        </div>
                    </div>
                    <div class="col-lg-2 hidden-md hidden-sm hidden-xs">
                    </div>
                   </div>';

            if (!empty($this->_['editID']) && $this->_['editID'] == $value['ID']) {
                $lastHeader = "";

                foreach ($this->_['editMeals'] as $key => $value2) {
                    array_walk($value2, 'htmlCallback');
                    echo '<div class="row singleEntry">';
                    if ($value2['headline'] != $lastHeader) {
                        echo '<div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div><div class="col-lg-8 col-md-12 k_side-bordered"><h4>'.$value2['headline'].'</h4></div><div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div></div><div class="row singleEntry">';
                        $lastHeader = $value2['headline'];
                    }

                    echo '<div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>';
                    echo '<div class="col-lg-8 col-md-12 k_side-bordered">';
                    echo '
                    <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="edit'.$value2['ID'].'-titleAddon"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span> Titel:</span>
                            <input type="text" name="title['.$value2['ID'].']" class="form-control" value="'.$value2['title'].'" aria-describedby="edit'.$value2['ID'].'-titleAddon">
                        </div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="edit'.$value2['ID'].'-descAddon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>Beschreibung:</span>
                            <input type="text" name="descr['.$value2['ID'].']" class="form-control" value="'.$value2['descr'].'" aria-describedby="edit'.$value2['ID'].'-descAddon">
                        </div>
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="edit'.$value2['ID'].'-priceAddon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>Preis:</span>
                            <input type="text" name="price['.$value2['ID'].']" class="form-control" value="'.$value2['price'].'" aria-describedby="edit'.$value2['ID'].'-priceAddon">
                        </div>
                        ';
                    echo '</div><div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>';
                    echo '</div>';

                }

                echo '
                <div class="row">
                <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                <div class="col-lg-8 col-md-12 k_side-bordered">
                    <textarea class="form-control" name="werbetext['.$value['ID'].']" rows="5">'.$value['werbetext'].'</textarea>
                </div>
                <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                </div>
                ';

                echo '<div class="row submit-row"><div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                      <div class="col-lg-8 col-md-12 k_side-bordered">
                        <input type="submit" class="btn btn-default" name="tableSubmit" value="Speichern" />
                      </div>
                      <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div></div>';
            }

            echo '
                   <div class="row">
                    <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                    <div class="col-lg-8 k_table-controls">
                        <a href="'.BASE_URL.'admin/mittagstisch?token='.$this->_['token'].'&geschaeft='.$this->_['geschaeft'].'&edit='.$value['ID'].'"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Bearbeiten </a>&nbsp;
                        <a href="'.BASE_URL.'admin/mittagstisch?token='.$this->_['token'].'&geschaeft='.$this->_['geschaeft'].'&delete='.$value['ID'].'"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Löschen </a>&nbsp;
                        <a href="http://extern.panten.de/kauffeld/pdfController.php?page=mittagstisch&key=seftgojktruh89ui2jn2l1iu3z894&token='.$this->_['token'].'&subpage='.$this->_['geschaeft'].'&card='.$value['ID'].'" target="_blank"><span class="glyphicon glyphicon-save-file" aria-hidden="true"></span> PDF erstellen </a>&nbsp;
                        <!-- <a href="http://extern.panten.de/kauffeld/newsletter/newsletterController.php?type=mittagstisch&cardID='.$value['ID'].'&key=UyuJCQRwT2C4XJp2hur1SWaC6DlwV3PTVMhtiqxv&subpage='.$this->_['geschaeft'].'" target="_blank"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Als Newsletter versenden </a> -->
                    </div>
                    <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
                    </div>
                    ';

        }
    }

    // Button zur Erstellung eines neuen Mittagstischs

    echo '
    <div class="row">
        <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
        <div class="col-lg-8">
            <a href="'.BASE_URL.'admin/mittagstisch?token='.$this->_['token'].'&geschaeft='.$this->_['geschaeft'].'&create=1"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Neue leere Karte anlegen</a>
        </div>
        <div class="col-lg-2 hidden-md hidden-sm hidden-xs"></div>
    </div>
    ';
?>
