<div class="k_gray">
    <div class="k_content-container">
        <div class="table-responsive">
            <table class="table k_table">
                <?php
                foreach ($this->_['entries'] as $value) {
                    ?>
                    <tr>
                        <td>
                            <strong><?php echo $value['title']; ?></strong>
                            <small><?php echo $value['desc']; ?></small>
                        </td>
                        <td>
                            <small><?php echo $value['price'] ?> € / <?php echo $value['unit']; ?></small>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </div>
    </div>
</div>