<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 01.08.2016
 * Time: 14:12
 */
$p = $this;
?>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="2000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="<?php echo BASE_URL; ?>img/1_home_mittagstisch_xl.jpg" alt="Kauffeld Mittagstisch">
            <div class="carousel-caption k_carousel-caption-top">
                Herzlich Willkommen
            </div>
            <div class="carousel-caption">
                <div class="k_home-slider-caption"><a href="mittagstisch">Zum Mittagstisch</a></div>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo BASE_URL; ?>img/1_home_wochenangebot.jpg" alt="Kauffeld Wochenangebot">
            <div class="carousel-caption k_carousel-caption-top">
                Herzlich Willkommen
            </div>
            <div class="carousel-caption">
                <div class="k_home-slider-caption"><a href="wochenangebot">Zum Wochenangebot</a></div>
            </div>
        </div>
        <div class="item">
            <img src="<?php echo BASE_URL; ?>img/1_home_grill.jpg" alt="Kauffeld Wochenangebot">
            <div class="carousel-caption k_carousel-caption-top">
                Herzlich Willkommen
            </div>
            <div class="carousel-caption">
                <div class="k_home-slider-caption"><a href="wochenangebot">Zum Wochenangebot</a></div>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
