<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 01.08.2016
 * Time: 14:31
 */
$p = $this;

function linkActive($active, $link) {
    return ($active == $link ? 'class="active"' : '');
}
?>

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $p->_['title'];?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet/less" type="text/css" href="<?php echo BASE_URL; ?>less/styles.less"/>
    <script src="<?php echo BASE_URL; ?>js/less.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        function klapp(id) {
            if ($('#'+id).hasClass('hide')) {
                $('#'+id).removeClass('hide')
            }
            else {
                $('#'+id).addClass('hide');
            }
        }
    </script>
</head>
<body>

<div class="container">
    <div class="k_header">
    <div class="row">
        <div class="col-lg-1 hidden-xs hidden-sm hidden-md"><div class="k_head-bg">&nbsp;</div></div>
        <div class="col-lg-3 col-xs-12"><div class="k_logo"><a href="<?php echo BASE_URL; ?>home"><img src="<?php echo BASE_URL; ?>img/logo.png" alt="Metzgerei Kauffeld - Logo" class="img-responsive"></a></div></div>
        <div class="col-lg-2 hidden-xs hidden-sm hidden-md">&nbsp;<div class="k_head-bg">&nbsp;</div></div>
        <div class="col-lg-6 hidden-xs hidden-sm hidden-md"><div class="k_head-bg">&nbsp;</div></div>
    </div>
    </div>
</div>


<?php if (empty($p->_['hideNavi'])) { ?>
    <div class="container">
        <nav id="k_navigation">
            <div class="row">
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>mittagstisch" <?php echo linkActive($p->_['activeLink'], "mittagstisch"); ?>>Mittagstisch</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>wochenangebot" <?php echo linkActive($p->_['activeLink'], "wochenangebot"); ?>>Wochenangebot</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>catering" <?php echo linkActive($p->_['activeLink'], "catering"); ?>>Catering</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>aktuelles" <?php echo linkActive($p->_['activeLink'], "aktuelles"); ?>>Aktuelles</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>wirueberuns" <?php echo linkActive($p->_['activeLink'], "wirueberuns"); ?>>Wir über uns</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="<?php echo BASE_URL; ?>impressum" <?php echo linkActive($p->_['activeLink'], "impressum"); ?>>Kontakt</a>
                </div>
            </div>
        </nav>
    </div>
    <?php
}
?>


<?php if (!empty($p->_['error'])) { echo '<div class="container">'.$p->_['error'].'</div>'; } ?>

<?php
if (!empty($p->_['headImg'])) {
    ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-xs-12">
                <img src="<?php echo BASE_URL; ?><?php echo $p->_['headImg']; ?>" alt="Panoramabild Metzgerei Kauffeld Baden-Baden" class="img-responsive" />
            </div>
        </div>
    </div>
<?php
}


if (!empty($p->_['subNavi'])) {
?>
<div class="container">
    <div class="subnavi text-justify" style="width:100%">
        <?php
        foreach ($p->_['subNavi'] as $key => $value) {
            $active = ($p->_['subNavi_active'] == $key ? ' class="active"' : '');
            echo '<a href="'.BASE_URL.$p->_['activeLink']."/".$key.'"'.$active.'>'.$value.'</a>';
        }
        ?>
    </div>
</div>
<?php } ?>


<h1><?php echo $p->_['header']; ?></h1>
<div class="container k_content">
    <?php echo $p->_['pageContent']; ?>
</div>

<div class="container">
    <div class="k_footer">
        Heinrich Kauffeld | Wurst- und Fleischwaren | Wilhelm-Drapp-Str. 14 | D-76532 Baden-Baden | Telefon: 07221-5046690 | Fax: 50466999 | <a href="<?php echo BASE_URL; ?>impressum" style="color:#DFDFDF;">Impressum</a>
    </div>
</div>

</body>
</html>
