<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 01.08.2016
 * Time: 14:31
 */
$p = $this;

function linkActive($active, $link) {
    return ($active == $link ? 'class="active"' : '');
}
?>

<!DOCTYPE html>
<html lang="<?php echo $p->_['testData']; ?>">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $p->_['title'];?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet/less" type="text/css" href="less/styles.less"/>
    <script src="js/less.min.js" type="text/javascript"></script>
</head>
<body>

<div class="container">
    <div class="k_header">
    <div class="row">
        <div class="col-lg-1 -hidden-xs"><div class="k_head-bg">&nbsp;</div></div>
        <div class="col-lg-3 col-xs-12"><div class="k_logo"><a href="home"><img src="img/logo.png" alt="Metzgerei Kauffeld - Logo" class="img-responsive"></a></div></div>
        <div class="col-lg-2 -hidden-xs">&nbsp;<div class="k_head-bg">&nbsp;</div></div>
        <div class="col-lg-6 -hidden-xs"><div class="k_head-bg">&nbsp;</div></div>
    </div>
    </div>
</div>

    <div class="container">
        <nav id="k_navigation">
            <div class="row">
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="mittagstisch" <?php echo linkActive($p->_['activeLink'], "mittagstisch"); ?>>Mittagstisch</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="wochenangebot" <?php echo linkActive($p->_['activeLink'], "wochenangebot"); ?>>Wochenangebot</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="catering" <?php echo linkActive($p->_['activeLink'], "catering"); ?>>Catering</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="aktuelles" <?php echo linkActive($p->_['activeLink'], "aktuelles"); ?>>Aktuelles</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="wirueberuns" <?php echo linkActive($p->_['activeLink'], "wirueberuns"); ?>>Wir über uns</a>
                </div>
                <div class="col-lg-2 col-sm-4 col-xs-12">
                    <a href="impressum" <?php echo linkActive($p->_['activeLink'], "impressum"); ?>>Kontakt</a>
                </div>
            </div>
        </nav>
    </div>

<?php if (!empty($p->_['error'])) { echo '<div class="container">'.$p->_['error'].'</div>'; } ?>

<?php
if (!empty($p->_['headImg'])) {
    ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-xs-12">
                <img src="<?php echo $p->_['headImg']; ?>" alt="Panoramabild Metzgerei Kauffeld Baden-Baden" class="img-responsive" />
            </div>
        </div>
    </div>
<?php
}
?>

<div class="container k_content">
    <?php echo $p->_['pageContent']; ?>
</div>

<div class="container">
    <div class="k_footer">
        Heinrich Kauffeld | Wurst- und Fleischwaren | Wilhelm-Drapp-Str. 14  D-76532 Baden-Baden | Telefon: 07221 - 50 46 590 | Fax: 07221 - 50 46 69 99
    </div>
</div>

</body>
</html>
