<div class="k_gray">
    <div class="k_content-container">
        <h2><small><?php echo $this->_['startDate'] . ' - ' . $this->_['endDate']; ?>, KW <?php echo $this->_['kw']; ?></small></h2>
        <div class="table-responsive">
            <table class="table k_table">
                <?php
                $lastHeader = "";
                foreach ($this->_['entries'] as $value) {
                    if ($value['title'] == "") {
                        continue;
                    }
                    if ($value['headline'] != $lastHeader) {
                        echo '
                        <tr>
                            <td colspan="2" class="k_head">'.$value['headline'].'</td>
                        </tr>
                        ';
                    }

                    $lastHeader = $value['headline'];
                    ?>
                    <tr>
                        <td>
                            <strong><?php echo $value['title']; ?></strong>
                            <small><?php echo $value['descr']; ?></small>
                        </td>
                        <td style="text-align:right;">
                            <small><?php echo $value['price'] ?></small>
                        </td>
                    </tr>
                    <?php
                }

                if (!empty($this->_['werbetext'])) {
                    ?>
                    <tr>
                        <td colspan="2"><?php echo nl2br($this->_['werbetext']); ?></td>
                    </tr>
                    <?php
                }
                ?>

            </table>
        </div>
        <br/><br/>
        <div>
            <small>
            <b>Die 14 Haupt-Allergene (Aushang im Ladengeschäft):</b><br/>
            1. Glutenhaltiges Getreide (Weizen, Roggen, Gerste, Hafer, Dinkel), 2.
            Krebstiere, 3.Eier, 4. Fisch, 5. Erdnüsse, 6. Soja, 7. Milch u.
            Sahneprodukte, 8. Schalenfrüchte (Mandel, Haselnuss), 9. Sellerie, 10. Senf,
            11. Sesam, 12. Schwefeldioxid u. Sulfite (Essigsäure + Weinessenz), 13.
            Lupinensamen, 14. Weichtiere (Tintenfisch, Schnecken)<br/><br/>
            Da bei der Herstellung der verschiedenen Speisen Kreuzkontaminationen nicht
            ausgeschlossen sind, können wir nicht dafür garantieren, dass in den
            angebotenen Speisen neben den gekennzeichneten noch weitere Inhaltsstoffe
            enthalten sind.
            </small>
        </div>
    </div>
</div>
