<?php
?>
<div class="k_gray">
    <div class="k_content-container">
        Sehr geehrte Kunden,<br/>
        hier können Sie sich in den Mail- und Faxverteiler für unsere Mittagskarten und unser Wochenangebot eintragen. Sie können einzeln auswählen, welche der Angebote Sie erhalten möchten. Weiterhin können Sie sich jederzeit mit einem Klick wieder austragen.

        <div>
            <form action="<?php echo BASE_URL; ?>NewsletterRegister" method="POST" accept-charset="UTF-8">
                <label for="adresse"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon_str">Str./Nr.</span>
                    <input type="text" class="form-control input-lg" style="width:70%" name="adresse" placeholder="Straße, Hausnummer" aria-describedby="addon_str">
                    <input type="text" class="form-control input-lg" style="width:30%" name="stadt" placeholder="PLZ, Stadt" aria-describedby="addon_plz">
                    <span class="input-group-addon" id="addon_plz">PLZ, Stadt.</span>
                </div>
                <label for="email"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon_email">E-Mail</span>
                    <input type="text" class="form-control input-lg" name="email" placeholder="E-Mail-Adresse" aria-describedby="addon_email">
                </div>
                <label for="fax"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon_fax">Fax</span>
                    <input type="text" class="form-control input-lg" name="fax" placeholder="Fax-Nummer" aria-describedby="addon_fax">
                </div>
                <label for="auswahl"></label>
                <div>
                    <label class="checkbox-inline"><input type="checkbox" name="wochenkarte" value="1">Wochenangebot</label>
                    <label class="checkbox-inline"><input type="checkbox" name="hauptgeschaeft" value="1">Mittagskarte Hauptgeschäft</label>
                    <label class="checkbox-inline"><input type="checkbox" name="rheinstrasse" value="1">Mittagskarte Rheinstrasse</label>
                </div>
                <br/><br/>
                <input type="submit" value="Registrieren" name="submit" class="btn btn-primary input-lg" />
            </form>
        </div>
    </div>
</div>
