<div class="k_gray">
    <div class="row">
        <div class="col-lg-2 col-sm-1 hidden-xs">&nbsp;</div>
        <div class="col-lg-4 col-sm-5 col-xs-12">
            <div class="k_content-container">
                <img class="img-responsive" src="<?php echo BASE_URL ?>img/6_wirueberuns_diedrei.jpg" />
            </div>
            <div class="k_content-container">
                Christiane Kauffeld, Bürokauffrau zuständig für Finanzen und Personal (Bildmitte)
                <br/><br/>
                Tanja Kauffeld, Bankkauffrau, zuständig für Rechnungswesen Einkauf und Marketing
                <br/><br/>
                Sabine Kauffeld, Metzgermeister, zuständig für die Filialen und Partyservice (rechts)
                <br/><br/>
                Das Unternehmen Kauffeld beschäftigt 45 Mitarbeiter und bildet jährlich zwischen 4 bis 6 Lehrlinge aus.<br/>

                2007 wurde das Unternehmen Kauffeld zu einem der familienfreundlichsten Betriebe in der Region ausgezeichnet.
            </div>
        </div>
        <div class="col-lg-4 col-sm-5 col-xs-12">
            <div class="k_content-container">
            Der Gründer Heinrich Kauffeld erlernte das Metzgerhandwerk von seinem Großvater im schwäbischen Munderkingen.
            <br/><br/>
            Im badischen Neuburgweier eröffnete 1966 der Metzgermeister Heinrich Kauffeld seine Metzgerei.
            <br/><br/>
            1979 übernahm Herr Kauffeld die Brill Schwarzwälder Fleischwaren GmbH in Baden-Baden.
            <br/><br/>
            1989 wurde das neue Produktionsgebäude in Baden Oos eingeweiht.
            <br/><br/>
            2005 nahm Herr Kauffeld seine Töchter Sabine, Christiane und Tanja in die Unternehmensführung mit auf.
            <br/><br/>
            Die Frauenpower stellt die Weichen für die Fortführung des Betriebes in zweiter Generation.
            </div>
        </div>
        <div class="col-lg-2 col-sm-1 hidden-xs">&nbsp;</div>
    </div>
</div>